### PR TITLE
Entity Relationship Diagram 

### PR DESCRIPTION
**Pull request by NoTengoBattery**
This pull request will:
  - Fix configuration files to make this scaffold work on a slightly newer Ruby version
  - Implement an ER graphic for the database structure

### CODE REVIEW

**Review by jubaan — CHANGES_REQUESTED** [review]
[![Microverse][microverse-shield]][microverse-url]
<div>
<h1 align="center"> ⚠️ 🛠️ ⚠️ 🛠️ Changes Required 🛠️ ⚠️ 🛠️ ⚠️ </h1>
<br />
<p><b>"Fail fast, fail often"</b> and don't let this discourage you, because <b>only by failing do we learn to succeed</b>.</p>
<details open="open">
  <summary>Review Summary</summary>
  <ol>
    <li><a href="#congrats"> 💯 Awesome work 👏🏼 👏🏼 </a></li>
    <li><a href="#mandatory"> ⚠️ Things to Improve </a> 🚨 🚨 </li>
    <li><a href="#optional"> 💡Nice to have and other comments ✍🏼 ✍🏼 </a></li>
    <li><a href="#contact"> 🧔🏼 About your Reviewer </a> (you don't know it... but we are just automated bots 🤖) </li>
    <li><a href="#help"> 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼 </a></li>
  </ol>
</details>
</div>

<h3 id="congrats"> 1. :100: Awesome work</h3>
<details close="close">
<summary> [click to open] Big or little achievements, but achievements at the end. <b>Feel proud that you're learning and improving everyday.</b></summary>



</details>

<hr>
<h3 id="mandatory"> 2. ⚠️ Things to Improve (or the To-Do list to get the project approved) </h3> 
<details close="close">
<summary> [click to open] Working on these observations will help you advance and get closer to the goal 🎯, postpone them or do them half-ways and they'll haunt you 👻 👻... FOREVER!! (It will feel like that, trust me). </summary>


- [ ] The ERD should point the PK and FK.
- [ ] Link should have also its own ID
- [ ] Use better naming for request, friendship is more descriptive, should have user and friend id and the status
- [ ] User should have an image_link attribute



</details>
<p><b>NOTE</b>This list is or could be divided in what is show in this comment and inline comments posted below.<p>
<hr>

<h3 id="optional"> 3. 💡 Nice to have and other comments </h3>
<details close="close">
<summary> [click to open] </h3></summary>


- [x] Nothing more to add.


</details>

<h3 id="contact"> 4. 🧔🏼 About your Reviewer </h3>
<details close="close">
<summary> [click to open] Say "hello world!" on Slack: @jubaan</summary>
<br />
<div align="center">
  <a src="https://www.github.com/jubaan">
    Julio Añoveros
  </a>
  <p>
    Julio Añoveros | @jubaan</br></br>
    <b>Full-stack Web Developer</b> and</br>
    🤖 Code Reviewer at <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a>:rocket:
  </p>
</div>
</details>

<h3 id="help"> 5. 🆘 <b> 😭 Feeling stuck? or Need help</b>? 🙏🏼 🙏🏼</h3>
<details close="close">
  <summary> [click to open] <b>Feel stuck?</b> </summary>
  <br>
  <p> First breath... just do it. Take 15-20 min away from the computer, stretch, meditate, do some exercise, drink water, or do whatever is necessary to distract your mind from the obstacle.</p>
  <p><b>Sometimes you just need to get away to see things with a new perspective.</b></p>
</details>

<details close="close">
  <summary> [click to open] <b>Need help?</b> </summary>
  <br>
  <p> Send me a DM in <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> Students Slack, you'll find me as @jubaan. If I'm not available there are other Code Reviewers you can contact. They'll help as well.</p>
  <p>Remember that <a href="https://www.microverse.org/?grsf=kfm2ej">Microverse</a> has other channels where you can get an answer to your questions:</p>
  <ol>
    <li>The <b>students channel 🧑‍🎓 </b> in slack,</li>
    <li>your <b>teammates 👥 </b>,</li>
    <li>your <b>mentor 👨🏼 👩🏼 </b>, and</li>
    <li><b>Student Success 🏫 </b>.</li>
  </ol>
  <p><b> DON'T hesitate to ask! </b></p>
</details>
<p>If all of the above doesn't help... get a <a href="https://rubberduckdebugging.com/">rubber duck</a> ... it would be great to own one 😄. </p>

<h2 align="center"> Keep up the great work :muscle: and Happy Coding :smiley: :computer:!! </h1>

[microverse-shield]: https://img.shields.io/badge/-microverse-%236F23FF?style=for-the-badge
[microverse-url]: https://www.microverse.org/?grsf=kfm2ej
[bootstrap-shield]: https://img.shields.io/badge/Bootstrap-white?style=for-the-badge&logo=bootstrap
[bootstrap-url]: https://www.microverse.org/?grsf=kfm2ej

**Comment by NoTengoBattery** [comment]
@jubaan Are you aware that this is the **first milestone**?
This code review is so bad. Please make a little bit more effort next time. Not bashing against you personally, sadly it's a pure fact.
image

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes Required :red_circle:**  

### To Highlight
- [x] Good use of Git flow. :100: 
- [x] Linter setting up correctly. :+1: 
- [x] Good introduction. :+1: 
- [x] Good Pull request description. :1st_place_medal: 

### To Improve :factory_worker: 

- [x] In your `User` table, we just need: name, encrypted_password, email and gravatar_url.
- [x] In your `User` table, you can remove : reset_password_token, reset_password_token_sent_at and remember_created_at as you are not going to save them in your table. They are just a function.
- [x] You can remove : created_at and updated_at columns as they will be generated automatically by rails.
- [x] Precise your Foreign key.
- [x] The association between `User` and `Friendship` should look like this:

`Explanation:`
-  One User can send many Friendships.
-  One Friendship is sent by only one User.
-  One User can receive many Friendships.
-  One Friendship is sent to only one User.

That's it, you can submit another code review request after making these changes :recycle: :innocent:
With all my respect :pray:
Rindra Josia

**Review by MahmoudBakr23 — CHANGES_REQUESTED** [review]
# **Changes Required 🛑♻**

<hr>

Hello there, good job building the ERD and working on the requested changes. However, there is still one more thing to do in order to get this milestone approved and move on to the next.😊

- [x] Please make sure to use Primary Keys (PK) correctly in your ERD tables. Currently, they're missing on all of the tables. (Note: the PK is optional in the friendship table)

<hr>

Please make the required changes to the ERD and ask for another review. 😊🙏
Good luck with the next and happy coding 👨‍💻💻

**Review by enaburekhan — APPROVED** [review]
# Status: Project Approved
Hi team!
Nice one:clap::clap:. Thank you for implementing the changes requested by the previous reviewers.
You can move on with the next milestone:walking:.

[Optional]

- Rename PK id to ID to differentiate them from the other keys.
- Create two columns on each table. One for the keys and the other for the names. It will make the ERD easier to read and understand. 

Kindly drop your questions :point_down: and ping me on slack @ Eric Enaburekhan to respond.
Happy hacking:blush:
Eric Enaburekhan

**Pull request merged**
